# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gophercloud:
        patterns:
          - "^github.com/gophercloud/"
      golang_x:
        patterns:
          - "^golang.org/x/"
      default:
        patterns:
          - "*"
