# Functional testing for blockstorage_v2 which was deprecated on Pike
# and completely removed on Xena
name: functional-blockstorage_v2
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    paths:
      - '.github/workflows/functional-blockstorage_v2.yml'
      - 'go.mod'
      - 'openstack/**blockstorage**'
      - '!**v3**'
jobs:
  functional-basic:
    strategy:
      fail-fast: false
      matrix:
        name: ["wallaby"]
        openstack_version: ["stable/wallaby"]
        ubuntu_version: ["20.04"]
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: blockstorage_v2 on OpenStack ${{ matrix.name }} with defaults and run basic acceptance tests
    steps:
      - name: Checkout TPO
        uses: actions/checkout@v4
      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.14
        with:
          branch: ${{ matrix.openstack_version }}
          enabled_services: 's-account,s-container,s-object,s-proxy'
      - name: Checkout go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.20'
      - name: Run TPO acceptance tests
        run: OS_BLOCKSTORAGE_V2=true ./scripts/acceptancetest.sh
        env:
          DEVSTACK_PATH: ${{ github.workspace }}/devstack
          ACCEPTANCE_TESTS_FILTER: 'blockstorage.*v2|v2.*blockstorage'
          OS_BRANCH: ${{ matrix.openstack_version }}
      - name: Generate logs on failure
        run: ./scripts/collectlogs.sh
        if: failure()
      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: functional-basic-${{ matrix.name }}
          path: /tmp/devstack-logs/*
